addpath('..\..\eeglab2024.0');
addpath('..\..\eeglab2024.0\plugins\erplab10.1');

n2_latency = [200 300]; % Time window where N2 is expected (in ms)
p3_latency = [300 500]; % Time window where P3 is expected (in ms)

% parameters
channels = 1:32;
n_bins = 1:3;
n_sets = 1:41;

% measures path
dirPath = 'ERP_Criterion_Good\Measures\';

% load erps generated
[ERP, ALLERP] = pop_loaderp( 'filename', {'ERPSET_Good_CRB_001.erp', 'ERPSET_Good_CRB_003.erp', 'ERPSET_Good_CRB_004.erp', 'ERPSET_Good_CRB_005.erp',...
 'ERPSET_Good_CRB_008.erp', 'ERPSET_Good_CRB_012.erp', 'ERPSET_Good_CRB_015.erp', 'ERPSET_Good_CRB_017.erp', 'ERPSET_Good_CRB_018.erp',...
 'ERPSET_Good_CRB_024.erp', 'ERPSET_Good_CRB_026.erp', 'ERPSET_Good_CRB_027.erp', 'ERPSET_Good_CRB_028.erp', 'ERPSET_Good_CRB_029.erp',...
 'ERPSET_Good_CRB_032.erp', 'ERPSET_Good_CRB_034.erp', 'ERPSET_Good_CRB_035.erp', 'ERPSET_Good_CRB_037.erp', 'ERPSET_Good_CRB_040.erp',...
 'ERPSET_Good_CRB_042.erp', 'ERPSET_Good_CRB_043.erp', 'ERPSET_Good_CRB_045.erp', 'ERPSET_Good_CRB_049.erp', 'ERPSET_Good_CRB_050.erp',...
 'ERPSET_Good_CRB_054.erp', 'ERPSET_Good_CRB_056.erp', 'ERPSET_Good_CRB_058.erp', 'ERPSET_Good_CRB_059.erp', 'ERPSET_Good_CRB_060.erp', 'ERPSET_Good_CRB_061.erp',...
 'ERPSET_Good_CRB_062.erp', 'ERPSET_Good_CRB_065.erp', 'ERPSET_Good_CRB_066.erp', 'ERPSET_Good_CRB_067.erp', 'ERPSET_Good_CRB_068.erp',...
 'ERPSET_Good_CRB_069.erp', 'ERPSET_Good_CRB_070.erp', 'ERPSET_Good_CRB_072.erp', 'ERPSET_Good_CRB_074.erp', 'ERPSET_Good_CRB_075.erp',...
 'ERPSET_Good_CRB_076.erp'}, 'filepath', 'ERP_Criterion_Good\' );

% measures
MA_P3 = pop_geterpvalues( ALLERP, p3_latency,  n_bins,  channels , 'Baseline', 'pre', 'Erpsets',  n_sets, 'FileFormat', 'wide', 'Filename',...
 sprintf('%sP3_MeanAmpl.xlsx', dirPath), 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'meanbl', 'PeakOnset',  1,...
 'Resolution',  10 );

MA_N2 = pop_geterpvalues( ALLERP, n2_latency,  n_bins,  channels , 'Baseline', 'pre', 'Erpsets',  n_sets, 'FileFormat', 'wide', 'Filename',...
 sprintf('%sN2_MeanAmpl.xlsx', dirPath), 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'meanbl', 'PeakOnset',  1,...
 'Resolution',  10 );

LAT_P3 = pop_geterpvalues( ALLERP, p3_latency,  n_bins,  channels , 'Erpsets', n_sets, ...
    'Baseline', 'pre', 'FileFormat', 'wide', 'Filename', sprintf('%sP3_Latency.xlsx', dirPath), ...
    'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'PeakOnset',  1, ...
    'Peakpolarity', 'positive', 'Peakreplace', 'absolute', 'Resolution', 10, 'Warning', 'on');

LAT_N2 = pop_geterpvalues( ALLERP, n2_latency,  n_bins,  channels, 'Erpsets', n_sets, ...
    'Baseline', 'pre', 'FileFormat', 'wide', 'Filename', sprintf('%sN2_Latency.xlsx', dirPath), ...
    'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'PeakOnset',  1, ...
    'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution', 10, 'Warning', 'on');


%%
% dirPath_ = 'ERP_Criterion_All\Measures\';
% 
% % load erps generated
% [ERP, ALLERP] = pop_loaderp( 'filename', {'ERPSET_All_CRB_001.erp', 'ERPSET_All_CRB_003.erp', 'ERPSET_All_CRB_004.erp', 'ERPSET_All_CRB_005.erp',...
%  'ERPSET_All_CRB_008.erp', 'ERPSET_All_CRB_012.erp', 'ERPSET_All_CRB_015.erp', 'ERPSET_All_CRB_017.erp',...
%  'ERPSET_All_CRB_018.erp', 'ERPSET_All_CRB_024.erp', 'ERPSET_All_CRB_026.erp', 'ERPSET_All_CRB_027.erp', 'ERPSET_All_CRB_028.erp', 'ERPSET_All_CRB_029.erp',...
%  'ERPSET_All_CRB_032.erp', 'ERPSET_All_CRB_034.erp', 'ERPSET_All_CRB_035.erp', 'ERPSET_All_CRB_037.erp', 'ERPSET_All_CRB_040.erp',...
%  'ERPSET_All_CRB_042.erp', 'ERPSET_All_CRB_043.erp', 'ERPSET_All_CRB_045.erp', 'ERPSET_All_CRB_049.erp', 'ERPSET_All_CRB_050.erp',...
%  'ERPSET_All_CRB_054.erp', 'ERPSET_All_CRB_056.erp', 'ERPSET_All_CRB_058.erp', 'ERPSET_All_CRB_059.erp', 'ERPSET_All_CRB_060.erp', 'ERPSET_All_CRB_061.erp',...
%  'ERPSET_All_CRB_062.erp', 'ERPSET_All_CRB_065.erp', 'ERPSET_All_CRB_066.erp', 'ERPSET_All_CRB_067.erp', 'ERPSET_All_CRB_068.erp',...
%  'ERPSET_All_CRB_069.erp', 'ERPSET_All_CRB_070.erp', 'ERPSET_All_CRB_072.erp', 'ERPSET_All_CRB_074.erp', 'ERPSET_All_CRB_075.erp', 'ERPSET_All_CRB_076.erp'},...
%  'filepath', 'ERP_Criterion_All\' );
% 
% % measures
% MA_P3 = pop_geterpvalues( ALLERP, p3_latency,  n_bins,  channels , 'Baseline', 'pre', 'Erpsets',  n_sets, 'FileFormat', 'wide', 'Filename',...
%  sprintf('%sP3_MeanAmpl.xlsx', dirPath), 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'meanbl', 'PeakOnset',  1,...
%  'Resolution',  10 );
% 
% MA_N2 = pop_geterpvalues( ALLERP, n2_latency,  n_bins,  channels , 'Baseline', 'pre', 'Erpsets',  n_sets, 'FileFormat', 'wide', 'Filename',...
%  sprintf('%sN2_MeanAmpl.xlsx', dirPath), 'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'meanbl', 'PeakOnset',  1,...
%  'Resolution',  10 );
% 
% LAT_P3 = pop_geterpvalues( ALLERP, p3_latency,  n_bins,  channels , 'Erpsets', n_sets, ...
%     'Baseline', 'pre', 'FileFormat', 'wide', 'Filename', sprintf('%sP3_Latency.xlsx', dirPath), ...
%     'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'PeakOnset',  1, ...
%     'Peakpolarity', 'positive', 'Peakreplace', 'absolute', 'Resolution', 10, 'Warning', 'on');
% 
% LAT_N2 = pop_geterpvalues( ALLERP, n2_latency,  n_bins,  channels, 'Erpsets', n_sets, ...
%     'Baseline', 'pre', 'FileFormat', 'wide', 'Filename', sprintf('%sN2_Latency.xlsx', dirPath), ...
%     'Fracreplace', 'NaN', 'InterpFactor',  1, 'Measure', 'peaklatbl', 'PeakOnset',  1, ...
%     'Peakpolarity', 'negative', 'Peakreplace', 'absolute', 'Resolution', 10, 'Warning', 'on');