addpath('..\..\eeglab2024.0');
addpath('..\..\eeglab2024.0\plugins\erplab10.1');

% load erps generated
[ERP, ALLERP] = pop_loaderp( 'filename', {'ERPSET_Good_CRB_001.erp', 'ERPSET_Good_CRB_003.erp', 'ERPSET_Good_CRB_004.erp', 'ERPSET_Good_CRB_005.erp',...
'ERPSET_Good_CRB_008.erp', 'ERPSET_Good_CRB_012.erp', 'ERPSET_Good_CRB_015.erp', 'ERPSET_Good_CRB_017.erp', 'ERPSET_Good_CRB_018.erp',...
'ERPSET_Good_CRB_024.erp', 'ERPSET_Good_CRB_026.erp', 'ERPSET_Good_CRB_027.erp', 'ERPSET_Good_CRB_028.erp', 'ERPSET_Good_CRB_029.erp',...
'ERPSET_Good_CRB_032.erp', 'ERPSET_Good_CRB_034.erp', 'ERPSET_Good_CRB_035.erp', 'ERPSET_Good_CRB_037.erp', 'ERPSET_Good_CRB_040.erp',...
'ERPSET_Good_CRB_042.erp', 'ERPSET_Good_CRB_043.erp', 'ERPSET_Good_CRB_045.erp', 'ERPSET_Good_CRB_049.erp', 'ERPSET_Good_CRB_050.erp',...
'ERPSET_Good_CRB_054.erp', 'ERPSET_Good_CRB_056.erp', 'ERPSET_Good_CRB_058.erp', 'ERPSET_Good_CRB_059.erp', 'ERPSET_Good_CRB_060.erp', ...
'ERPSET_Good_CRB_061.erp', 'ERPSET_Good_CRB_062.erp', 'ERPSET_Good_CRB_065.erp', 'ERPSET_Good_CRB_066.erp', 'ERPSET_Good_CRB_067.erp', ...
'ERPSET_Good_CRB_068.erp', 'ERPSET_Good_CRB_069.erp', 'ERPSET_Good_CRB_070.erp', 'ERPSET_Good_CRB_072.erp', 'ERPSET_Good_CRB_074.erp', ...
'ERPSET_Good_CRB_075.erp', 'ERPSET_Good_CRB_076.erp'}, 'filepath', 'ERP_Criterion_Good\' );

% Grand Averager
Grand_Avg = pop_gaverager( ALLERP , 'DQ_flag', 1, 'DQ_spec', 'DQ_spec_structure', 'Erpsets', 1:41, 'ExcludeNullBin', 'on', 'SEM', 'on' );
% Grand_Avg_save = pop_savemyerp(Grand_Avg, 'erpname', 'Grand_Avg', 'filename', 'Grand_Avg.erp', 'Warning', 'on');

%%

% load .erp with grand averager
Grand_Avg_ERP = pop_loaderp( 'filename', 'Grand_Avg.erp', 'filepath', 'C:\Users\gabri\OneDrive\Documents\Cognitive_Effort\ERPs\' );

% plot in P3 electrode
pop_ploterps( Grand_Avg_ERP,  1,  14 , 'Axsize', [ 0.05 0.08], 'BinNum', 'on', 'Blc', 'pre', 'Box', [ 1 1], 'ChLabel', 'on', 'FontSizeChan',  10,...
 'FontSizeLeg',  12, 'FontSizeTicks',  10, 'LegPos', 'none', 'Linespec', {'k-' }, 'LineWidth',  1, 'Position', [ 82.875 14.2857 106.875 31.9048],...
 'SEM', 'on', 'Style', 'Classic', 'Tag', 'ERP_figure', 'Transparency',  0.8, 'xscale', [ -200.0 1196.0   -200:200:1000 ], 'YDir',...
 'normal', 'yscale', [ -4.0 4.0   -4:4 ] );