function createfigure(X1, YMatrix1, XData1, YData1, YData2, YData3, YData4, YData5, YData6, Y1, XData2, YData7, XData3, XData4, XData5, XData6, XData7)
%CREATEFIGURE(X1, YMatrix1, XData1, YData1, YData2, YData3, YData4, YData5, YData6, Y1, XData2, YData7, XData3, XData4, XData5, XData6, XData7)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  YDATA5:  line ydata
%  YDATA6:  line ydata
%  Y1:  vector of plot y data
%  XDATA2:  line xdata
%  YDATA7:  line ydata
%  XDATA3:  line xdata
%  XDATA4:  line xdata
%  XDATA5:  line xdata
%  XDATA6:  line xdata
%  XDATA7:  line xdata

%  Auto-generated by MATLAB on 25-Jan-2025 12:16:45

% Create figure
figure1 = figure('PaperType','<custom>',...
    'PaperSize',[8.93541666666667 7.48333333333333],...
    'Name','<< My Viewer >>',...
    'Color',[1 1 1],...
    'Renderer','painters');

% Create axes
axes1 = axes('Position',...
    [0.0254975129048623 0.0548519439933677 0.964707710742209 0.727665538524115]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'DisplayName','Conneg, FirstBreak','LineWidth',3,...
    'Color',[0 0 0]);
set(plot1(1),'LineStyle','-.',...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);
set(plot1(2),'MarkerSize',4);
set(plot1(3),'LineWidth',1,'DisplayName','');

% Create text
text('FontSize',16,'String','\muV','Position',[14 4.9 0]);

% Create line
line(XData1,YData1,'LineWidth',1);

% Create line
line(XData1,YData2,'LineWidth',1);

% Create line
line(XData1,YData3,'LineWidth',1);

% Create line
line(XData1,YData4,'LineWidth',1);

% Create line
line(XData1,YData5,'LineWidth',1);

% Create line
line(XData1,YData6,'LineWidth',1);

% Create plot
plot(YData3,Y1,'LineWidth',1,'Color',[0 0 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','-3.0',...
    'Position',[-28 -3 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','-1.5',...
    'Position',[-28 -1.5 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'Position',[-28 0 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','1.5',...
    'Position',[-28 1.5 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','3.0',...
    'Position',[-28 3 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','4.5',...
    'Position',[-28 4.5 0]);

% Create line
line(XData2,YData7,'LineWidth',1);

% Create line
line(YData3,YData7,'LineWidth',1);

% Create line
line(XData3,YData7,'LineWidth',1);

% Create line
line(XData4,YData7,'LineWidth',1);

% Create line
line(XData5,YData7,'LineWidth',1);

% Create line
line(XData6,YData7,'LineWidth',1);

% Create line
line(XData7,YData7,'LineWidth',1);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','-200',...
    'Position',[-200 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'Position',[-0.11 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','200',...
    'Position',[200 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','400',...
    'Position',[400 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','600',...
    'Position',[600 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','800',...
    'Position',[800 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','1000 ms',...
    'Position',[1000 -0.055 0]);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.4 5.5]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color','none','XColor','none','XTick',zeros(1,0),'YColor','none',...
    'YTick',zeros(1,0));
% Create axes
axes('Position',[0.13 0.822412587412587 0.775 0.102587412587413]);
axis off

% Create line
annotation(figure1,'line',[0.47 0.47],[0.512650151668352 0.377148634984833],...
    'LineWidth',1.5);

% Create doublearrow
annotation(figure1,'doublearrow',[0.161978661493695 0.469447138700291],...
    [0.403448938321537 0.402426693629929],'LineStyle','-.');

% Create doublearrow
annotation(figure1,'doublearrow',[0.161978661493695 0.410281280310378],...
    [0.558 0.558],'LineStyle','-.');

% Create line
annotation(figure1,'line',[0.411 0.411],[0.6125 0.377148634984833],...
    'LineWidth',1.5);

% Create rectangle
annotation(figure1,'rectangle',...
    [0.366488845780797 0.318503538928211 0.139815712900096 0.344792719919112],...
    'LineStyle','none',...
    'FaceColor',[0.831372559070587 0.815686285495758 0.7843137383461],...
    'FaceAlpha',0.6);

% Create line
annotation(figure1,'line',[0.367604267701261 0.50533462657614],...
    [0.661285136501517 0.661274014155713],'LineWidth',1);

% Create line
annotation(figure1,'line',[0.436 0.436],...
    [0.660262891809909 0.675429726996967],'LineWidth',1);

% Create textbox
annotation(figure1,'textbox',...
    [0.2 0.554095045500506 0.156 0.037411526794742],'String',{'P300 Latency'},...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11,...
    'FontName','Verdana',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',[0.2 0.4 0.156 0.037411526794742],...
    'String','P300 Latency',...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',11,...
    'FontName','Verdana',...
    'FitBoxToText','off');

% Create textbox
annotation(figure1,'textbox',...
    [0.40837148399612 0.675429726996967 0.0533161978661496 0.0303336703741153],...
    'String','P300',...
    'LineStyle','none',...
    'HorizontalAlignment','center',...
    'FontSize',11,...
    'FontName','Verdana',...
    'FitBoxToText','off');

