function createfigure(ZData1, YData1, XData1, CData1, xdata2, ydata2, zdata2, ZData3, YData3, XData3, X1, Y1, X2, Y2, Z1, XMatrix1, Y3, Z2, X3, Y4, Z3)
%CREATEFIGURE(ZData1, YData1, XData1, CData1, xdata2, ydata2, zdata2, ZData3, YData3, XData3, X1, Y1, X2, Y2, Z1, XMatrix1, Y3, Z2, X3, Y4, Z3)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata
%  XDATA2:  contour x
%  YDATA2:  contour y
%  ZDATA2:  contour z
%  ZDATA3:  patch zdata
%  YDATA3:  patch ydata
%  XDATA3:  patch xdata
%  X1:  vector of plot x data
%  Y1:  vector of plot y data
%  X2:  vector of plot3 x data
%  Y2:  vector of plot3 y data
%  Z1:  vector of plot3 z data
%  XMATRIX1:  matrix of plot3 x data
%  Y3:  vector of plot3 y data
%  Z2:  vector of plot3 z data
%  X3:  vector of plot3 x data
%  Y4:  vector of plot3 y data
%  Z3:  vector of plot3 z data

%  Auto-generated by MATLAB on 25-Jan-2025 12:17:51

% Create figure
figure('Tag','Scalp_figure',...
    'Name','<< ERP_GA_high >>  Plot ERP map by Bins x latency',...
    'Color',[1 1 1]);
colormap(gray);

% Create axes
axes1 = axes('Position',[0.05 0.05 0.9 0.9]);
axis off
hold(axes1,'on');

% Create surface
surface('ZData',ZData1,'YData',YData1,'XData',XData1,'EdgeColor','none',...
    'CData',CData1);

% Create contour
contour(xdata2,ydata2,zdata2,'EdgeColor',[0.2 0.2 0.2],...
    'LevelList',[-4.7604817871113 -4.14723144019939 -3.53398109328748 -2.92073074637557 -2.30748039946366 -1.69423005255175 -1.08097970563984 -0.467729358727928 0.145520988183982 0.758771335095893 1.3720216820078 1.98527202891971]);

% Create patch
patch('ZData',ZData3,'YData',YData3,'XData',XData3,'FaceColor',[1 1 1],...
    'EdgeColor','none');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0 0 0]);

% Create plot3
plot3(X2,Y2,Z1,'LineWidth',2,'Color',[0 0 0]);

% Create multiple line objects using matrix input to plot3
plot3(XMatrix1,Y3,Z2,'LineWidth',2,'Color',[0 0 0]);

% Create plot3
plot3(X3,Y4,Z3,'MarkerSize',10,'Marker','.','LineWidth',1,...
    'LineStyle','none',...
    'Color',[0 0 0]);

% Create text
text('FontSize',9,'String','Fp1',...
    'Position',[-0.130462270170431 0.432298416497797 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','Fz','Position',[0.01 0.227272727272727 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','F3',...
    'Position',[-0.180703148802981 0.235498776199082 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','F7',...
    'Position',[-0.357734997443158 0.267175114678397 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','FC5',...
    'Position',[-0.313109525076305 0.130544721947969 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','FC1',...
    'Position',[-0.098759643859742 0.112623908133829 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','C3',...
    'Position',[-0.217272727272727 1.39164408994017e-17 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','T7',...
    'Position',[-0.444545454545455 2.78328817988035e-17 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','CP5',...
    'Position',[-0.315338633476298 -0.12488580059912 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','CP1',...
    'Position',[-0.098759643859742 -0.112623908133829 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','Pz','Position',[0.01 -0.227272727272727 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','P3',...
    'Position',[-0.180703148802981 -0.235498776199082 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','P7',...
    'Position',[-0.357734997443158 -0.267175114678397 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','O1',...
    'Position',[-0.130462270170431 -0.432298416497797 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','Oz',...
    'Position',[0.0100000000000001 -0.454545454545455 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','O2',...
    'Position',[0.150462270170431 -0.432298416497797 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','P4',...
    'Position',[0.200703148802981 -0.235498776199082 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','P8',...
    'Position',[0.377734997443158 -0.267175114678397 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','CP6',...
    'Position',[0.335338633476298 -0.12488580059912 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','CP2',...
    'Position',[0.118759643859742 -0.112623908133829 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','Cz','Position',[0.01 0 2.1],'Visible','on');

% Create text
text('FontSize',9,'String','C4',...
    'Position',[0.237272727272727 1.39164408994017e-17 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','T8',...
    'Position',[0.464545454545455 2.78328817988035e-17 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','FC6',...
    'Position',[0.335338633476298 0.12488580059912 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','FC2',...
    'Position',[0.118759643859742 0.112623908133829 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','F4',...
    'Position',[0.200703148802981 0.235498776199082 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','F8',...
    'Position',[0.377734997443158 0.267175114678397 2.1],...
    'Visible','on');

% Create text
text('FontSize',9,'String','Fp2',...
    'Position',[0.150462270170431 0.432298416497797 2.1],...
    'Visible','on');

% Create title
title({'High EI'},'FontSize',20,'FontName','Verdana');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.525 0.525]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.525 0.525]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CLim',[-5.64241874072437 2.7284484946232],'DataAspectRatio',...
    [1 1 1],'PlotBoxAspectRatio',[1 1 2.0952380952381]);
