function createfigure(X1, YMatrix1, XData1, YData1, YData2, YData3, YData4, YData5, YData6, Y1, XData2, YData7, XData3, XData4, XData5, XData6, XData7)
%CREATEFIGURE(X1, YMatrix1, XData1, YData1, YData2, YData3, YData4, YData5, YData6, Y1, XData2, YData7, XData3, XData4, XData5, XData6, XData7)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  YDATA5:  line ydata
%  YDATA6:  line ydata
%  Y1:  vector of plot y data
%  XDATA2:  line xdata
%  YDATA7:  line ydata
%  XDATA3:  line xdata
%  XDATA4:  line xdata
%  XDATA5:  line xdata
%  XDATA6:  line xdata
%  XDATA7:  line xdata

%  Auto-generated by MATLAB on 25-Jan-2025 12:17:24

% Create figure
figure1 = figure('PaperType','<custom>',...
    'PaperSize',[8.93541666666667 7.48333333333333],...
    'Name','<< My Viewer >>',...
    'Color',[1 1 1],...
    'Renderer','painters');

% Create axes
axes1 = axes('Position',...
    [0.0254975129048623 0.0548519439933677 0.964707710742209 0.727665538524115]);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'DisplayName','First-Latter difference',...
    'LineWidth',3,...
    'Color',[0 0 0]);
set(plot1(2),'LineWidth',1,'DisplayName','');
set(plot1(3),'LineStyle','-.',...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Create text
text('FontSize',16,'String','\muV','Position',[14 4.9 0]);

% Create line
line(XData1,YData1,'LineWidth',1);

% Create line
line(XData1,YData2,'LineWidth',1);

% Create line
line(XData1,YData3,'LineWidth',1);

% Create line
line(XData1,YData4,'LineWidth',1);

% Create line
line(XData1,YData5,'LineWidth',1);

% Create line
line(XData1,YData6,'LineWidth',1);

% Create plot
plot(YData3,Y1,'LineWidth',1,'Color',[0 0 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','-3.0',...
    'Position',[-28 -3 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','-1.5',...
    'Position',[-28 -1.5 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'Position',[-28 0 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','1.5',...
    'Position',[-28 1.5 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','3.0',...
    'Position',[-28 3 0]);

% Create text
text('HorizontalAlignment','right','FontSize',16,'String','4.5',...
    'Position',[-28 4.5 0]);

% Create line
line(XData2,YData7,'LineWidth',1);

% Create line
line(YData3,YData7,'LineWidth',1);

% Create line
line(XData3,YData7,'LineWidth',1);

% Create line
line(XData4,YData7,'LineWidth',1);

% Create line
line(XData5,YData7,'LineWidth',1);

% Create line
line(XData6,YData7,'LineWidth',1);

% Create line
line(XData7,YData7,'LineWidth',1);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','-200',...
    'Position',[-200 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'Position',[-0.11 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','200',...
    'Position',[200 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','400',...
    'Position',[400 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','600',...
    'Position',[600 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','800',...
    'Position',[800 -0.055 0]);

% Create text
text('VerticalAlignment','top','HorizontalAlignment','center','FontSize',16,...
    'String','1000 ms',...
    'Position',[1000 -0.055 0]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-234.9 1230.9]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-4.4 5.5]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color','none','XColor','none','XTick',[],'YColor','none','YTick',...
    []);
% Create axes
axes('Position',[0.13 0.822412587412587 0.775 0.102587412587413]);
axis off

% Create line
annotation(figure1,'line',[0.456353055286132 0.456353055286132],...
    [0.194652173913043 0.577856420626895],...
    'Color',[0.24705882370472 0.24705882370472 0.24705882370472],...
    'LineWidth',2);

% Create line
annotation(figure1,'line',[0.43258971871969 0.43258971871969],...
    [0.192124368048534 0.575328614762385],...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'LineWidth',2,...
    'LineStyle','-.');

% Create textarrow
annotation(figure1,'textarrow',[0.521823472356936 0.455868089233754],...
    [0.59353993933266 0.552072800808898],'String',{'Mean Latency','High EI'},...
    'LineWidth',1,...
    'HorizontalAlignment','left',...
    'FontSize',11,...
    'FontName','Verdana');

% Create textarrow
annotation(figure1,'textarrow',[0.368574199806014 0.429679922405432],...
    [0.140546006066734 0.206268958543984],...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176],...
    'String',{'Mean Latency','Low EI'},...
    'LineWidth',1,...
    'LineStyle','-.',...
    'FontSize',11,...
    'FontName','Verdana');

