# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HkXtIRG4RBr9rIAPwWayx66Cl6msTEgv
"""

import pandas as pd
import statsmodels.api as sm
import numpy as np
from sklearn.utils import resample
import itertools

# Load the data
df = pd.read_excel("Gabriel_AnalysisMultisourceCC.xlsx")
df.set_index('Subject', inplace=True) 

# Clean column names
df.columns = [col.replace('-', '_').replace(' ', '_') for col in df.columns]

# Define variables
X_variables = [
    'P3_P3_B1_MA', 'N2_P3_B1_MA', 'P3_P3_B1B2_MA', 'N2_P3_B1B2_MA', 
    'P3_P3_B1_LAT', 'N2_P3_B1_LAT', 'P3_P3_B1B2_LAT', 'N2_P3_B1B2_LAT',
    'FirstRTMT', 'FirstRT', 'FirstMT', 'FirstMinusLatterRTMT', 'FirstMinusLatterRT', 'FirstMinusLatterMT',
    'TotalDurationFixation_BreakSide', 'ET1', 'TotalDurationFixation_FollowSide', 'ET2', 
    'Total_duration_of_whole_fixations_BreakSide', 'ET3', 'Total_duration_of_whole_fixations_FollowSide', 
    'ET4', 'Total_duration_of_Visit_BreakSide', 'ET5', 'Total_duration_of_Visit_FollowSide', 
    'ET6', 'Total_duration_of_Glances_BreakSide', 'ET7', 'Total_duration_of_Glances_FollowSide', 'ET8',
    'Average_duration_of_fixations_BreakSide', 'ET9', 'Average_duration_of_fixations_FollowSide', 'ET10', 
    'Average_duration_of_whole_fixations_BreakSide', 'ET11', 'Average_duration_of_whole_fixations_FollowSide', 
    'ET12', 'Average_duration_of_Visit_BreakSide', 'ET13', 'Average_duration_of_Visit_FollowSide', 'ET14', 
    'Average_duration_of_Glances_BreakSide', 'ET15', 'Average_duration_of_Glances_FollowSide', 'ET16', 
    'Minimum_duration_of_fixations_BreakSide', 'ET17', 'Minimum_duration_of_fixations_FollowSide', 'ET18', 
    'Minimum_duration_of_whole_fixations_BreakSide', 'ET19', 'Minimum_duration_of_whole_fixations_FollowSide', 
    'ET20', 'Minimum_duration_of_Visit_BreakSide', 'ET21', 'Minimum_duration_of_Visit_FollowSide', 'ET22', 
    'Minimum_duration_of_Glances_BreakSide', 'ET23', 'Minimum_duration_of_Glances_FollowSide', 'ET24', 
    'Maximum_duration_of_fixations_BreakSide', 'ET25', 'Maximum_duration_of_fixations_FollowSide', 'ET26', 
    'Maximum_duration_of_whole_fixations_BreakSide', 'ET27', 'Maximum_duration_of_whole_fixations_FollowSide', 
    'ET28', 'Maximum_duration_of_Visit_BreakSide', 'ET29', 'Maximum_duration_of_Visit_FollowSide', 'ET30', 
    'Maximum_duration_of_Glances_BreakSide', 'ET31', 'Maximum_duration_of_Glances_FollowSide', 'ET32', 
    'Number_of_fixations_BreakSide', 'ET33', 'Number_of_fixations_FollowSide', 'ET34', 
    'Number_of_whole_fixations_BreakSide', 'ET35', 'Number_of_whole_fixations_FollowSide', 'ET36', 
    'Number_of_Visits_BreakSide', 'ET37', 'Number_of_Visits_FollowSide', 'ET38', 
    'Number_of_Glances_BreakSide', 'ET39', 'Number_of_Glances_FollowSide', 'ET40', 
    'Number_of_saccades_BreakSide', 'ET41', 'Number_of_saccades_FollowSide', 'ET42', 
    'Duration_of_first_whole_fixation_BreakSide', 'ET43', 'Duration_of_first_whole_fixation_FollowSide', 'ET44', 
    'Time_to_entry_saccade_BreakSide', 'ET45', 'Time_to_entry_saccade_FollowSide', 'ET46', 
    'Time_to_exit_saccade_BreakSide', 'ET47', 'Time_to_exit_saccade_FollowSide', 'ET48', 
    'Peak_velocity_of_entry_saccade_BreakSide', 'ET49', 'Peak_velocity_of_entry_saccade_FollowSide', 'ET50', 
    'Peak_velocity_of_exit_saccade_BreakSide', 'ET51', 'Peak_velocity_of_exit_saccade_FollowSide', 'ET52',
    'FirstPD', 'MLatterPD', 'FirstMinusLatterRTMT', 'FirstMAD', 'FirstAUC', 
    'MLatterMAD', 'MLatterAUC', 'FirstMinusLatterMAD', 'FirstMinusLatterAUC'
]
Y_variables = ['MeanEntPassion', 'MeanEntIntention']

M_variables = ['MOpportunityRecognition1', 'MeanEntPassion']

# Convert relevant columns to numeric
all_variables = X_variables + Y_variables + M_variables
for var in all_variables:
    if var in df.columns:
        df[var] = pd.to_numeric(df[var], errors='coerce')

# Initialize results DataFrame
results_df = pd.DataFrame(columns=[
    'X_Variable', 'Y_Variable', 'M_Variable', 'Indirect_Effect', 'Direct_Effect', 'Total_Effect', 'Proportion_Mediated',
    'Bootstrap_CI_Lower', 'Bootstrap_CI_Upper', 'P-Value_a', 'P-Value_b', 'P-Value_c_prime', 'Significance'
])

# Custom mediation analysis function
def mediation_analysis(df, x_var, y_var, m_var, n_iterations=1000):
    # Remove rows with missing values
    df_subset = df.dropna(subset=[x_var, y_var, m_var])

    if df_subset.empty:
        return None

    # Fit the mediator model (M ~ X)
    mediator_model = sm.OLS(df_subset[m_var], sm.add_constant(df_subset[x_var])).fit()

    # Fit the outcome model (Y ~ X + M)
    outcome_model = sm.OLS(df_subset[y_var], sm.add_constant(df_subset[[x_var, m_var]])).fit()

    # Calculate direct and indirect effects
    a = mediator_model.params[x_var]  # Path a
    b = outcome_model.params[m_var]  # Path b
    indirect_effect = a * b
    c_prime = outcome_model.params[x_var]  # Path c'
    total_effect = indirect_effect + c_prime
    proportion_mediated = indirect_effect / total_effect

    # Bootstrap to get confidence intervals for the indirect effect
    bootstrap_indirect_effects = np.zeros(n_iterations)
    for i in range(n_iterations):
        df_boot = resample(df_subset)
        mediator_model_boot = sm.OLS(df_boot[m_var], sm.add_constant(df_boot[x_var])).fit()
        outcome_model_boot = sm.OLS(df_boot[y_var], sm.add_constant(df_boot[[x_var, m_var]])).fit()
        a_boot = mediator_model_boot.params[x_var]
        b_boot = outcome_model_boot.params[m_var]
        bootstrap_indirect_effects[i] = a_boot * b_boot

    lower_bound = np.percentile(bootstrap_indirect_effects, 2.5)
    upper_bound = np.percentile(bootstrap_indirect_effects, 97.5)

    # Determine significance
    significance = 'Not Significant'
    if mediator_model.pvalues[x_var] < 0.05 and outcome_model.pvalues[m_var] < 0.05:
        significance = 'Significant'

    # Return results as a dictionary
    return {
        'X_Variable': x_var,
        'Y_Variable': y_var,
        'M_Variable': m_var,
        'Indirect_Effect': indirect_effect,
        'Direct_Effect': c_prime,
        'Total_Effect': total_effect,
        'Proportion_Mediated': proportion_mediated,
        'Bootstrap_CI_Lower': lower_bound,
        'Bootstrap_CI_Upper': upper_bound,
        'P-Value_a': mediator_model.pvalues[x_var],
        'P-Value_b': outcome_model.pvalues[m_var],
        'P-Value_c_prime': outcome_model.pvalues[x_var],
        'Significance': significance
    }

# Perform mediation analysis for each combination of variables
for y_var, x_var, m_var in itertools.product(Y_variables, X_variables, M_variables):
    try:
        result = mediation_analysis(df, x_var, y_var, m_var)
        if result is not None:
            results_df = pd.concat([results_df, pd.DataFrame([result])], ignore_index=True)
    except Exception as e:
        print(f"Error processing X: {x_var}, Y: {y_var}, M: {m_var}. Error: {e}")

# Save results to Excel
results_df.to_excel('Mediation_Results1.xlsx', index=False)